//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baslangic1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ilan
    {
        [Key]
        public int Id { get; set; }
        [DisplayName("Baþlýk")]
        public string baslik { get; set; }
        [DisplayName("Baþlangýç Tarihi")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> baslangic { get; set; }
        [DisplayName("Bitiþ Tarihi")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> bitis { get; set; }
        [DisplayName("Açýklama")]
        public string aciklama { get; set; }
        [DisplayName("Pozisyon")]
        public string pozisyon { get; set; }
    }
}
