//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baslangic1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yenimvcEntities : DbContext
    {
        public yenimvcEntities()
            : base("name=yenimvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<basvuru> basvuru { get; set; }
        public virtual DbSet<ilan> ilan { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<resim> resim { get; set; }
        public virtual DbSet<Sorular> Sorular { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
