//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baslangic1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class resim
    {
        public int resimId { get; set; }
        public string isim { get; set; }
        public byte[] goruntu { get; set; }
        public HttpPostedFileBase goruntuDosya { get; set; }
    }
}
