//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baslangic1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.basvuru = new HashSet<basvuru>();
        }

        [Key]
        public int userId { get; set; }
        [DisplayName("Parola")]
        public string parola { get; set; }
        [DisplayName("Ad")]
        public string isim { get; set; }
        [DisplayName("Soyad")]
        public string soyisim { get; set; }
        [DisplayName("Bölüm")]
        public string bölüm { get; set; }
        [DisplayName("Öğretim Türü")]
        public string öğretim_türü { get; set; }
        [DisplayName("Telefon")]
        public string telefon { get; set; }
        [DisplayName("Mail")]
        public string mail { get; set; }
        [DisplayName("Not Ortalaması")]
        public Nullable<double> Not_Ortalamasi { get; set; }
        public Nullable<int> cd_modifier { get; set; }
        public Nullable<System.DateTime> dt_modified { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }

        public Nullable<int> isAdmin { get; set; }
        public string applicationList { get; set; }
        public byte[] picture { get; set; }
        [DisplayName("CV")]
        public HttpPostedFileBase pictureFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<basvuru> basvuru { get; set; }
    }
}

